//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitabxanaProyekti.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emeliyyat_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emeliyyat_Table()
        {
            this.Ceza_Table = new HashSet<Ceza_Table>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Kitab { get; set; }
        public Nullable<int> Istifadeci { get; set; }
        public Nullable<byte> Isci { get; set; }
        public Nullable<System.DateTime> GoturulmeTarix { get; set; }
        public Nullable<System.DateTime> QaytarmaTarix { get; set; }
        public Nullable<System.DateTime> IstifadeciQaytarmaTarix { get; set; }
        public Nullable<bool> EmeliyyatVeziyyet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ceza_Table> Ceza_Table { get; set; }
        public virtual Isci_Table Isci_Table { get; set; }
        public virtual Istifadeci_Table Istifadeci_Table { get; set; }
        public virtual Kitab_Table Kitab_Table { get; set; }
    }
}
