//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitabxanaProyekti.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstifadeciMesaj_Table
    {
        public int ID { get; set; }
        public string Gonderen { get; set; }
        public string QebulEden { get; set; }
        public string Movzu { get; set; }
        public string Mesaj { get; set; }
        public Nullable<System.DateTime> Tarix { get; set; }
    }
}
