//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitabxanaProyekti.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitab_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitab_Table()
        {
            this.Emeliyyat_Table = new HashSet<Emeliyyat_Table>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public Nullable<byte> Kategoriya { get; set; }
        public Nullable<int> Yazici { get; set; }
        public string NesrTarix { get; set; }
        public string YayinEvi { get; set; }
        public string Seyfe { get; set; }
        public Nullable<bool> Veziyyet { get; set; }
        public string Resim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emeliyyat_Table> Emeliyyat_Table { get; set; }
        public virtual Kategoriya_Table Kategoriya_Table { get; set; }
        public virtual Yazici_Table Yazici_Table { get; set; }
    }
}
